name: Create pre-release

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: jMeter tests
    runs-on: ubuntu-latest
    services:
      megen:
        image: php:8.0-apache
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/var/www/html/
    steps:
      - uses: actions/checkout@v2
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.2
        with:
          testFilePath: tests/all.jmx
          outputReportsFolder: reports/
      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
          
          
  pre-release:
    name: GitHub Pre-release
    runs-on: "ubuntu-latest"
    needs: test

    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "beta"
          prerelease: true
          title: "Development Build"


  beta-deploy:
    name: Beta deploy
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME_BETA }}
        password: ${{ secrets.FTP_PASSWORD_BETA }}
        protocol: ftps
        exclude: .git*
          - .git*/**
          - **/.git*/**
          - .dockerignore
          - logo/raw-svg
          - logo/raw-svg/*
          - logo/megen.png
          - Dockerfile
          - tests
          - tests/*
          - LICENSE
          - README.md
          - stack.yml
        security: strict
